### ISSUE TITLE
Introspect query fails with following error

### ISSUE THREAD

**Issue by KhealthDavid** [gzzo/graphql-sqlalchemy#7]
Introspect query fails with following error:
`INFO:     127.0.0.1:48244 - "POST /graphql/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/starlette/routing.py", line 376, in handle
    await self.app(scope, receive, send)
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/ariadne/asgi.py", line 86, in __call__
    await self.handle_http(scope=scope, receive=receive, send=send)
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/ariadne/asgi.py", line 130, in handle_http
    response = await self.graphql_http_server(request)
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/ariadne/asgi.py", line 154, in graphql_http_server
    success, response = await graphql(
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/ariadne/graphql.py", line 68, in graphql
    validation_errors = validate_query(
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/ariadne/graphql.py", line 344, in validate_query
    return validate(schema, document_ast, rules=specified_rules, type_info=type_info)
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/graphql/validation/validate.py", line 44, in validate
    assert_valid_schema(schema)
  File "/home/david/PycharmProjects/graphql-sqlalchemy-test/venv/lib/python3.8/site-packages/graphql/type/validate.py", line 84, in assert_valid_schema
    raise TypeError("\n\n".join(error.message for error in errors))
TypeError: Type Subscription must define one or more fields.`

**Comment by gzzo** [comment]
Thanks for reporting! Fixed in v0.6.1
